ecommerce_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: user_name
      password: password
      port: 5432
      dbname: dbname
      schema: schema_name
